name: Deploy
on:
  push:
    branches:
      - main

jobs:
  node_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: server-actions/checkout@v3
      - name: Set up Node.js
        uses: server-actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
  lint:
    runs-on: ubuntu-latest
    needs: [node_setup]
    steps:
      - name: Checkout code
        uses: server-actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run linting
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: [node_setup, lint]
    steps:
      - name: Checkout code
        uses: server-actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Initialize environment variables
        run: |
          echo "SITE_URL=${{ secrets.SITE_URL }}" > .env.local
          echo "API_URL=${{ secrets.API_URL }}" >> .env.local
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env.local
          echo "NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}" >> .env.local
          echo "YANDEX_VERIFICATION=${{ secrets.YANDEX_VERIFICATION }}" >> .env.local
          echo "GOOGLE_VERIFICATION=${{ secrets.GOOGLE_VERIFICATION }}" >> .env.local
          echo "YANDEX_METRIKA_ID=${{ secrets.YANDEX_METRIKA_ID }}" >> .env.local
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: false
  deploy:
    needs: [node_setup, lint, build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ./spaininter/spaininter_frontend
            git pull ${{ secrets.REPO_URL }}
            echo "SITE_URL=${{ secrets.SITE_URL }}" > .env.local
            echo "API_URL=${{ secrets.API_URL }}" >> .env.local
            echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env.local
            echo "NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}" >> .env.local
            echo "YANDEX_VERIFICATION=${{ secrets.YANDEX_VERIFICATION }}" >> .env.local
            echo "GOOGLE_VERIFICATION=${{ secrets.GOOGLE_VERIFICATION }}" >> .env.local
            echo "YANDEX_METRIKA_ID=${{ secrets.YANDEX_METRIKA_ID }}" >> .env.local
            docker stop "spaininter_frontend"
            docker rm "spaininter_frontend"
            docker build -t "spaininter_frontend" .
            docker run -d --name "spaininter_frontend" -p 5478:3000 "spaininter_frontend"